In [6]:
import numpy as np

In [7]:
list = [1,2,3,4,5,6]
arr = np.array(list)

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(6,)

In [12]:
list1 = [1]
list2 = [2]
list3 = [3]

arr1 = np.array([list1,list2,list3])

In [13]:
arr1

array([[1],
       [2],
       [3]])

In [14]:
arr1.shape

(3, 1)

In [19]:
list1 = [1,2,3,4,5]
list2 = [2,3,4,5,6]
list3 = [3,4,5,6,7]

arr2 = np.array([list1,list2,list3])

In [23]:
# 2 dimensional array will always start with 2 opening ([[]) and 2 closing (]]) 
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr2.shape

(3, 5)

In [24]:
#reshaping 2d array, remember the number of elements should be same eg. if 15 elements are present before reshaping then the same number of elements should be present after reshaping
arr2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [26]:
#indedxing in array
arr

array([1, 2, 3, 4, 5, 6])

In [29]:
arr[1:5] #from position 1 to position 4 starting with 0

array([2, 3, 4, 5])

In [30]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [36]:
arr2[:,:] # this will print the array as it is

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [38]:
arr2[0:3,0:2]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [43]:
arr2[1:4,3:5] 
# this can also be written as
arr2[1:,3:]
# basically we can ignore the last columns and it will be selected by default

array([[5, 6],
       [6, 7]])

In [45]:
arr2[1,1:4]

array([3, 4, 5])

In [46]:
arr2[1:,2:4]

array([[4, 5],
       [5, 6]])

In [74]:
#copy and broadcasting
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [75]:
arr1[3:]=100

In [76]:
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [82]:
arr1=arr

In [83]:
arr

array([1, 2, 3, 4, 5, 6])

In [84]:
arr[3:]=1000

In [85]:
arr

array([   1,    2,    3, 1000, 1000, 1000])

In [86]:
arr1

array([   1,    2,    3, 1000, 1000, 1000])

In [ ]:
# now we can see above that arr has also changed the elements of arr2 so to preven this we use copy function instead of arr1=arr we write arr1=arr.copy()

In [91]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1[3:]=100
print(arr1)

[  1   2   3 100 100 100 100 100 100]


In [93]:
arr1=arr.copy()
arr[3:]=500
print(arr)

[  1   2   3 500 500 500]


In [94]:
arr1

array([  1,   2,   3, 500, 500, 500])

In [95]:
arr

array([  1,   2,   3, 500, 500, 500])

In [98]:
# arrange function
arr3 = np.arange(0, 20)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [109]:
arr3 = np.arange(0,20).reshape(5,4)

In [110]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [118]:
# linspace function
print(np.linspace(0, 10, 20, dtype=int))

[ 0  0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9 10]


In [124]:
# randint funcction
np.random.randint(0,10,20)

array([2, 1, 4, 9, 7, 1, 7, 0, 8, 4, 0, 1, 6, 8, 0, 7, 4, 2, 2, 9])